# Generated by Django 3.0.5 on 2020-05-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='path',
            old_name='path_id',
            new_name='id',
        ),
    ]
