# Generated by Django 3.0.5 on 2020-05-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200525_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='dep_sequence',
            new_name='dept_sequence',
        ),
    ]
