# Generated by Django 3.0.5 on 2020-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField( primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('est_days', models.CharField(max_length=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('image_qr', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
