# Generated by Django 3.0.5 on 2020-05-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200519_1152'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.Register'),
        ),
    ]
