# Generated by Django 3.0.5 on 2020-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_update_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
