# Generated by Django 3.0.5 on 2020-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_auto_20200522_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='file_type',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
